## Required packages for generating site
required_pkgs <- c(
    "CVXR",
    "kableExtra",
    "stringr",
    "ggplot2",
    "devtools",
    "l1tf",
    "glmnet",
    "boot",
    "tidyr",
    "profvis",
    "ggforce",
    "nnls",
    "markovchain",
    "quantreg",
    "isotone",
    "MASS",
    "RColorBrewer",
    "grid",
    "Matrix",
    "expm",
    "dplyr",
    "survey")

