baseurl = "https://cvxr.rbind.io/"
languageCode = "en-us"
metadataformat = "yaml"
title = "CVXR"
theme = "hugo-alabaster-theme"
relativeURLs = true

disqusShortname = ""
googleAnalytics = ""

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "\\.rst$", "\\.Rhistory$"]

[params]
	name = ""
	description = "Disciplined Convex Programming in R"
	
	github_user   = "bnaras"
	github_repo   = "cvxr_docs"
	github_banner = true

	custom_css = []
	custom_js  = []

	favicon = "favicon.ico"

  #highlightjsVersion = "9.11.0"
  #highlightjsCDN = "//cdn.bootcss.com"
  #highlightjsLang = ["r", "yaml"]
  #highlightjsTheme = "github"

  MathJaxCDN = "//cdn.bootcss.com"
  MathJaxVersion = "2.7.1"
    
[params.sidebar]
	logo = "favicon.ico"
	
	github_button  = true
	travis_button  = false
	codecov_button = false
	gratipay = ""

	show_relations = true

[[menu.main]]
    name = "Home"
         identifier = "Level-01"
    	 url = "/index.html"
	 weight = -22

[params.footer]
	copyright = "Anqi Fu, Balasubramanian Narasimhan, Stephen Boyd"
	show_powered_by = true

[[menu.main]]
    name = "Package Docs"
    	 url = "https://anqif.github.io/CVXR"
	 weight = -21

[[menu.main]]
    name = "Tutorial"
         identifier = "tutorial"
	 parent = "Level-01"
    	 url = "/post/cvxr_examples/"
	 weight = -20

[[menu.main]]
    name = "A Quick Intro"
    	 url = "/post/examples/cvxr_intro/"
	 weight = -19

[[menu.main]]
    name = "A Longer Intro"
    	 url = "/post/examples/cvxr_gentle-intro/"
	 weight = -18

[[menu.main]]
    name = "Tutorial Examples"
    	 url = "/post/cvxr_examples/"
	 weight = -17

[[menu.main]]
    name = "FAQ"
    	 url = "/post/cvxr_faq/"
	 weight = -16

[[menu.main]]
    name = "DCP"
    	 url = "/post/cvxr_dcp/"
	 weight = -16

[[menu.main]]
    name = "Function Reference"
    	 url = "/post/cvxr_functions/"
	 weight = -15
