baseurl = "https://cvxr.rbind.io/"
languageCode = "en-us"
metadataformat = "yaml"
title = "CVXR"
theme = "hugo-alabaster-theme"
relativeURLs = true

disqusShortname = ""
googleAnalytics = ""

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "\\.rst$", "\\.Rhistory$"]

[params]
	name = ""
	description = "Disciplined Convex Programming in R"
	
	github_user   = "cvxgrp"
	github_repo   = "CVXR"
	github_banner = true

	custom_css = []
	custom_js  = []

	favicon = "favicon.ico"

  #highlightjsVersion = "9.11.0"
  #highlightjsCDN = "//cdn.bootcss.com"
  #highlightjsLang = ["r", "yaml"]
  #highlightjsTheme = "github"

  MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
  MathJaxVersion = "2.7.5"
    
[params.sidebar]
	logo = "favicon.ico"
	
	github_button  = true
	travis_button  = false
	codecov_button = false
	gratipay = ""

	show_relations = true

[params.footer]
	copyright = "Anqi Fu, Balasubramanian Narasimhan, Stephen Boyd"
	show_powered_by = true

[[menu.main]]
    name = "Home"
         identifier = "Level-01"
    	 url = "/"
	 weight = -23

[[menu.main]]
    name = "What's new in 1.0"
    	 url = "/cvxr_examples/whats_new_1.0"
	 weight = -22


[[menu.main]]
    name = "Package docs"
    	 url = "https://anqif.github.io/CVXR"
	 weight = -21

[[menu.main]]
    name = "Quick intro"
    	 url = "/cvxr_examples/cvxr_intro/"
	 weight = -19

[[menu.main]]
    name = "Longer intro"
    	 url = "/cvxr_examples/cvxr_gentle-intro/"
	 weight = -18

[[menu.main]]
    name = "Tutorial examples"
    	 url = "/examples/"
	 weight = -17

[[menu.main]]
    name = "FAQ"
    	 url = "/cvxr_faq/"
	 weight = -16

[[menu.main]]
    name = "DCP"
    	 url = "/cvxr_dcp/"
	 weight = -16

[[menu.main]]
    name = "Function reference"
    	 url = "/cvxr_functions/"
	 weight = -15
