---
site: blogdown:::blogdown_site
---

## What is `cvxr`?

`cvxr` is an R package that provides an object-oriented modeling
  language for convex optimization, similar to `CVX`, `CVXPY`,
  `YALMIP`, and `Convex.jl`. It allows the user to formulate convex
  optimization problems in a natural mathematical syntax rather than
  the restrictive standard form required by most solvers. The user
  specifies an objective and set of constraints by combining
  constants, variables, and parameters using a library of functions
  with known mathematical properties. `cvxr` then applies signed
  disciplined convex programming (DCP) to verify the problem's
  convexity. Once verified, the problem is converted into standard
  conic form using graph implementations and passed to a cone solver
  such as [ECOS](https://github.com/embotech/ecos)
  or [SCS](https://github.com/cvxgrp/scs). 

## Installing `cvxr`

`cvxr` is installed like any other R package
from [CRAN](https://cloud.r-project.org).

## Acknowledgements

We are grateful to Steven Diamond, John Miller, and Paul K. Rosenfield
for their contributions to the software's development. In particular,
we are indebted to Steven Diamond for his work
on [CVXPY](http://www.cvxpy.org/en/latest/); most of `cvxr` code,
documentation, and examples were ported from his Python library.


