---
title: Convex Optimization in R
author: Anqi Fu and Balasubramanian Narasimhan
date: '2017-10-30'
slug: cvxr
bibliography: bibtex/cvxr_refs.bib
type: homepage
---

## What is `CVXR`?

`CVXR` is an R package that provides an object-oriented modeling
language for convex optimization, similar to `CVX`, `CVXPY`, `YALMIP`,
and `Convex.jl`. It allows the user to formulate convex optimization
problems in a natural mathematical syntax rather than the restrictive
standard form required by most solvers. The user specifies an
objective and set of constraints by combining constants, variables,
and parameters using a library of functions with known mathematical
properties. `CVXR` then applies
signed [disciplined convex programming (DCP)](/post/cvxr_dcp) to
verify the problem’s convexity. Once verified, the problem is
converted into standard conic form using graph implementations and
passed to a cone solver such
as [ECOS](https://github.com/embotech/ecos)
or [SCS](https://github.com/cvxgrp/scs).

## `CVXR` paper

A preliminary draft our paper is
available
[here](https://web.stanford.edu/~boyd/papers/cvxr_paper.html). 

## Status

Although `CVXR` continues to be developed
on [Github](https://github.com/anqif), the current release implements all of
the `CVXPY` atoms except for `geo_mean` and parameters. The latter is
not an impediment since any parameter can be replaced by a variable.

The focus of the development is mostly on speeding up the
canonicalization and construction of problem data in `CVXR`.

## Installing `CVXR`

`CVXR` is installed like any other R package
from [CRAN](https://cloud.r-project.org).

## Documentation

A [video of the talk](http://channel9.msdn.com/Events/useR-international-R-User-conference/useR2016/CVXR-An-R-Package-for-Modeling-Convex-Optimization-Problems) by [Anqi Fu](https://web.stanford.edu/~anqif)
at [useR! 2016](http://user2016.r-project.org) provides a good
overview.

An introductory vignette is installed with the package and can be
viewed using `vignette("cvxr_intro", package = "CVXR")`.

A large set of examples, many ported from `CVXPY`, are available on
this site in the [Examples](/post/cvxr_examples/) section.

## Citing `CVXR`

If you use `CVXR` in your work, please consider citing the paper
by @fu:naras:boyd:2017 below.


## Acknowledgements

We are grateful
to
[Steven Diamond](https://web.stanford.edu/~stevend2/),
[John Miller](https://people.eecs.berkeley.edu/~miller_john/), and
Paul Kunsberg Rosenfield for their contributions to the software’s
development. In particular, we are indebted to Steven Diamond for his
work on [CVXPY](http://www.cvxpy.org/en/latest/). Most of `CVXR`'s code,
documentation, and examples were ported from his Python library.

## About this site

Much of the documentation on this site was modified
from [`CVXPY`](https://cvxpy.org) in a semi-automated way. 

This site was constructed
using [R markdown documents](http://rmarkdown.rstudio.com/), the
wonderful [blogdown](https://cloud.r-package.org/package="blogdown")
package by [Yihui Xie](https://yihui.name/), and
the
[Hugo Alabaster theme](https://themes.gohugo.io/theme/hugo-alabaster-theme/). The
pages are served out of
the [CVXR docs](https://github.com/bnaras/cvxr_docs) repository.

## References
