---
title: Warm Starts
author: Anqi Fu, David Kang and Balasubramanian Narasimhan
date: '2020-02-22'
categories:
  - Version 1.0 features
slug: warm_starts
params:
  mode: test
---

A new feature in 1.0 is warm starts for one of our solvers in
`OSQP`. Having warm starts allows the user to retain data of a
particular problem and change parameters of the problem without
repeating any of the calculations.


## Lasso Example

We will demonstrate this in a simple lasso problem:

$$
	\begin{array}{ll} \underset{x, \lambda}{\mbox{minimize}} & \frac{1}{2}||Ax - b||_2^2 + \lambda ||x||_1\\
	\mbox{subject to} & \lambda > 0
	\end{array}
$$


```{r prereqs, message = FALSE, echo = FALSE}
library(CVXR)
library(Matrix)
```

```{r}
#Problem data
set.seed(1)
m <- 2000
n <- 1000
A <- Matrix(rnorm(m*n), nrow = m, ncol = n)
b <- rnorm(m)

#Construct problem
gamma <- Parameter(pos = TRUE)
x <- Variable(n)
obj <- Minimize(.5 * sum_squares(A%*%x - b) + gamma * norm1(x))
constraint <- list(x >= 0)
prob <- Problem(obj, constraint)

#Solve first time
value(gamma) = 1
result <- solve(prob, solver = "OSQP", warm_start = T) #warm_start = T is not necessary for the first time
print(paste0("First solve time is ", result$solve_time))

#Solve second time
value(gamma) = 2
result <- solve(prob, solver = "OSQP", warm_start = T)
print(paste0("Second solve time is ", result$solve_time))

```

As you can see, there is a very significant speed up with warm starts
than without. 
